[tool.poetry]
name = "embaralha palavra"
version = "0.1.0"
description = ""
authors = ["Isaak Gomes de Araújo <isaaksalus@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"